config/routes.rb
Rails.application.routes.draw do
  resources :relationships, only: [:create, :destroy]
  get 'lectures/index'
  get 'lectures/new'
  devise_for :users
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :posts do
    resources :comments, only: [:create]
    collection do
      get 'search'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    mount_uploader :image, ImageUploader
    has_many :comments, dependent: :destroy
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :user
    belongs_to :follow, class_name: 'User'
  
    validates :user_id, presence: true
    validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :posts, dependent: :destroy
         has_many :comments, dependent: :destroy
         has_many :relationships
         has_many :followings, through: :relationships, source: :follow
         has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
         has_many :followers, through: :reverse_of_relationships, source: :user
         validates :name, presence: true 
         validates :profile, length: { maximum: 200 } 
         def follow(other_user)
          unless self == other_user
            self.relationships.find_or_create_by(follow_id: other_user.id)
          end
        end
      
        def unfollow(other_user)
          relationship = self.relationships.find_by(follow_id: other_user.id)
          relationship.destroy if relationship
        end
      
        def following?(other_user)
          self.followings.include?(other_user)
        end
      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
         
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
    def configure_permitted_parameters
      
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile])
    end
  
  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
      post = Post.find(params[:post_id])
      comment = post.comments.build(comment_params) 
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path)
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path)
      end
    end
  
    private
  
      def comment_params
        params.require(:comment).permit(:content)
      end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :set_q, only: [:index, :search]
    before_action :authenticate_user!
    def index
      if params[:search] == nil
          @posts= Post.all.page(params[:page]).per(2)
      elsif params[:search] == ''
          @posts= Post.all.page(params[:page]).per(3)
        else
          #部分検索
          @posts = Post.where("body LIKE ? ",'%' + params[:search] + '%').page(params[:page]).per(3)
      end
      
  end
    def new
        @post = Post.new
      end
    def create
        post = Post.new(post_params)
        post.user_id = current_user.id
        if post.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
    end
    end
    def show
        @post = Post.find(params[:id])
        @comments = @post.comments
        @comment = Comment.new
    end
    def edit
        @post = Post.find(params[:id])
    end
    def update
        post = Post.find(params[:id])
        if post.update(post_params)
          redirect_to :action => "show", :id => post.id
        else
          redirect_to :action => "new"
    end
    end  
    def destroy
        post = Post.find(params[:id])
        post.destroy
        redirect_to action: :index
      end
      def search
        @results = @q.result
      end
      private
      def set_q
        @q = Post.ransack(params[:q])
      end
    def post_params
        params.require(:post).permit(:title,:media,:actor,:genre,:image,:overall,:level,:comment)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    before_action :set_user
    
   
    def create
      following = current_user.follow(@user)
      if following.save
        flash[:success] = 'ユーザーをフォローしました'
        redirect_to @user
      else
        flash.now[:alert] = 'ユーザーのフォローに失敗しました'
        redirect_to @user
      end
    end
  
    def destroy
      following = current_user.unfollow(@user)
      if following.destroy
        flash[:success] = 'ユーザーのフォローを解除しました'
        redirect_to @user
      else
        flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
        redirect_to @user
      end
    end
  
    private
    def set_user
      @user = User.find(params[:follow_id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
      
        user = User.find(params[:id])
        @posts = Post.all.page(params[:page]).per(2)
      
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
          percent = calPercent.round
          return percent.to_s
        else
          return 0
        end
      end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FMS(Find Media Site)</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>FMS(Find Media Site)</h1>
      <div class="header-list">
      <ul>
        <a href="#"><u><li><%= link_to "新規投稿へ", new_post_path %></li></u></a>
        
        <a href="#"><u><li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li></u></a>
        <a href="#"><u><li><%= link_to "Reseach一覧に戻る", posts_path %></li></u></a>
      </ul>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
     <p>Copyright © GeekSalon All Rights Reserved.</p>
    </footer>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="sinki">

    <div class="minao">
      <%= form_for @post do |f| %>
      <font face="Comic Sans MS">title</font>
      <%= f.text_field :title, :size => 50 %>
      <br>
      <font face="Comic Sans MS">media</font>
      <%= f.text_field :media, :size => 50 %>
      <br>
      <font face="Comic Sans MS">actor</font>
      <%= f.text_field :actor, :size => 50 %> 
      <br>
      <font face="Comic Sans MS">genre</font>
      <%= f.text_field :genre, :size => 50 %> 
      <br>
    </div>
      <div class="henshuu">
        <h4>総合評価</h4>
        <%= f.radio_button :overall, 5 ,id: 'star1'%>
        <label for="star1"><span class="text">最高</span>★</label>

        <%= f.radio_button :overall, 4 ,id: 'star2'%>
        <label for="star2"><span class="text">良い</span>★</label>

        <%= f.radio_button :overall, 3 ,id: 'star3'%>
        <label for="star3"><span class="text">普通</span>★</label>

        <%= f.radio_button :overall, 2 ,id: 'star4'%>
        <label for="star4"><span class="text">悪い</span>★</label>

        <%= f.radio_button :overall, 1 ,id: 'star5'%>
        <label for="star5"><span class="text">最悪</span>★</label>
        <br>
    
        <%= f.label :comment, '一言' %>
        <br>
        <%= f.text_field :comment, :size => 50 %>
        <br>
        <font face="Comic Sans MS">image</font>
        <%= f.file_field :image %>
        <br>
          <div class="kensaku">
            <%= f.submit "編集する" %>  
          </div>
      </div>
    
  <% end %>
</div> 

app/views/posts/index.html.erb
<div class="parent">


  <%= search_form_for @q, url: search_posts_path do |f| %>
  

  <p>
  <div class="field">
    <font face="Comic Sans MS">title</font>
    <%= f.search_field :title_cont %>
    <br>
    
    
    <font face="Comic Sans MS">media</font>
    <%= f.search_field :media_cont %>
    <br>
    
    <font face="Comic Sans MS">actor</font>
    <%= f.search_field :actor_cont %>
    <br>

    <font face="Comic Sans MS">genre</font>
    <%= f.search_field :genre_cont %>

    <br>
    <div class="kensaku">
      <%= f.submit '検索' %>
      <% end %>
    </div>  
  </div>

      <div class="posts-container">
        <% @posts.each do |t| %>
        <p>
        <div class="left-container">
          <%= image_tag t.image_url, size: "250x200" if t.image? %>
          <br>
          <%= t.title %>
          <br>
          <hr>
          <%= t.media %>
          <br>
          <hr>
          <%= t.actor %>
          <br>
          <hr>
          <%= t.genre %>
          <br>
          <hr>
          <h3>総合評価：
          <span class="star-rating">
          <span class="star-rating-front" style="width: <%= getPercent(t.overall) %>%;">★★★★★</span>
          <span class="star-rating-back">★★★★★</span>
          </span> 
          </h3>
          <%= link_to "詳細へ", post_path(t.id) %>
          <br>
            <%= t.user.email %>
            <% if user_signed_in? %>
            <%= link_to "マイページへ", user_path(t.user_id) %>
            
            <% end %>
          
          </div> 
      <% end %>
        <div class="page">
            <%= paginate(@posts) %>
          </div>
</div>

app/views/posts/new.html.erb
<div class="sinki">


        <div class="haruto">
        <%= form_for @post do |f| %>
        <h5>新規投稿ページ</h5>

        <font face="Comic Sans MS">title</font>
        <%= f.text_field :title, :size => 50 %>
        <br>

        <font face="Comic Sans MS">media</font>
        <%= f.text_field :media, :size => 50 %>
        <br>

        <font face="Comic Sans MS">actor</font>
        <%= f.text_field :actor, :size => 50 %>
        <br>

        <font face="Comic Sans MS">genre</font>
        <%= f.text_field :genre, :size => 50 %>
        </div>

            <div class="hosi">

            

            <h4>総合評価</h4>
            <%= f.radio_button :overall, 5 ,id: 'star1'%>
            <label for="star1"><span class="text">最高</span>★</label>

            <%= f.radio_button :overall, 4 ,id: 'star2'%>
            <label for="star2"><span class="text">良い</span>★</label>

            <%= f.radio_button :overall, 3 ,id: 'star3'%>
            <label for="star3"><span class="text">普通</span>★</label>

            <%= f.radio_button :overall, 2 ,id: 'star4'%>
            <label for="star4"><span class="text">悪い</span>★</label>

            <%= f.radio_button :overall, 1 ,id: 'star5'%>
            <label for="star5"><span class="text">最悪</span>★</label>


            <br>
            <%= f.label :comment, '一言' %>
            <br>   
            <%= f.text_field :comment, :size => 50 %>
            <font face="Comic Sans MS">image</font>
            <%= f.file_field :image %>
            <br>
            <div class="kensaku">
                <%= f.submit "投稿する" %>
            </div>
        </div>
                <% end %>

</div>

app/views/posts/search.html.erb
<div class="souiti">
  <div class="kekka">
    <% @results.each do |t| %>
      <p>
      <div class="eiga">
        <%= image_tag t.image_url, size: "250x200" if t.image? %>    
        <br>
        <%= t.title %>
        <br>
        <hr>
        <%= t.media %>
        <br>
        <hr>
        <%= t.actor %>
        <br>
        <hr>
        <%= t.genre %>
        <br>
        <hr>
        <%= t.user.email %>
        <br>
        <%= link_to "マイページへ", user_path(t.user_id) %>
        <br>
        <%= link_to "詳細へ", post_path(t.id) %>
        <%= link_to "編集する", edit_post_path(t.id) %>
        <%= link_to "削除する", post_path(t.id), method: :delete %>
      
      </div>  
    <% end %>
      
  </div>
</div>

app/views/posts/show.html.erb
<div class="shousai">
  <div class="youhiti">
    <%= image_tag @post.image_url, size: "400x500" if @post.image? %>
  </div>
    <div class="kuniyasu">
      <p><%= @post.title %></p>
      <hr>
      <p><%= @post.media %></p>
      <hr>
      <p><%= @post.actor %></p>
      <hr>
      <p><%= @post.genre %></p>
      <hr>
      <p><%= @post.comment %></p>
      <hr>
      <p><%= @post.created_at %></p>
      <hr>
    </div>

    <div class="comment-wrapper">
      <p>コメント一覧</p>
      <% @comments.each do |c| %>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    
      <% end %>
      <% if user_signed_in? %>
      <%= form_with(model: [@post, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
      <i class="far fa-comments"></i> コメントする
      <% end %>
      <% end %>
      <% end %>
      <%= link_to "編集する", edit_post_path(@post.id) %> 
    </div>
</div>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
    <% end %>
  <% end %>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="mypage">

  

  <div class="namae">
    <h4>マイページ</h4>
    <p>名前 : <%= @user.name %></p>
    <p>メールアドレス : <%= @user.email %></p>
    <p>プロフィール : <%= @user.profile %></p>
    <%= render 'relationships/follow_button', user: @user %>

    <% if current_user.id == @user.id %>
    <%= link_to "編集する", edit_user_registration_path %>
    <% end %>
  </div>

    <div class="takumi">
      
      <div class = "title">
      <h4>ユーザーの投稿一覧</h4>
      </div>
      
      <div class = "abc">
      <% @user.posts.each do |t| %>
      <div class="itiran">
        <%= image_tag t.image_url, size: "170x120" if t.image? %>
          <br>
          <%= t.title %>
          <br>
          <hr>
          <%= t.media %>
          <br>
          <hr>
          <%= t.actor %>
          <br>
          <hr>
          <%= t.genre %>
          <hr>
      </div>
      <% end %>
      </div>
    </div>    

</div>